#!/bin/bash

# Change to script directory
cd "$(dirname "$0")"

case $1 in
    copy | cp )
        ./utils/osscp $2 $3 $4 $5
        ;;

    rmrf )
        ./utils/ossrmrf $2 $3 $4 $5
        ;;

    ls )
        ./utils/ossls $2 $3 $4 $5
        ;;

    get-backup-count | gbc )
        ./utils/ossgbc
        ;;

    clear-backups | clear-backup | cb )
        ./utils/ossclearbackup
        ;;

    * )
        echo unknown argument $1

esac