#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"
max_keep_count=$(sed '/^max_keep_count=/!d;s/.*='// ../config)
backup_dir=$(sed '/^backup_dir=/!d;s/.*='// ../config)/
count=$(../utils/ossgbc)
backups=$(../utils/ossls $backup_dir -d | grep oss://)
if [[ $max_keep_count < 0 ]];
then
	echo bad max_keep_count
	exit
fi
if [[ $count -gt $max_keep_count || $count == $max_keep_count ]];
then
	array=(${backups//\n/ })
	len=${#array[@]}
	endp=$(expr $len - 4)
	for e in $(seq 1 $endp)
        do
                ../utils/ossrmrf "${array[$e]}" --force
        done
fi
